creation_rules:
  # All YAML files under wazuh/
  - path_regex: wazuh/.*\.yaml$
    encrypted_regex: ^(data)$
    yaml_keep_line_breaks: true

  # All YAML files under wazuh_managers/
  - path_regex: wazuh_managers/.*\.yaml$
    encrypted_regex: ^(data)$
    yaml_keep_line_breaks: true

  # .conf files under wazuh_managers/ (treated as binary)
  - path_regex: wazuh_managers/.*\.conf$
    encrypted_suffix: ".enc"
    input_type: "binary"

  # TLS files (.key and .crt) under syslog-ng-secrets/
  - path_regex: wazuh_managers/wazuh_conf/syslog-ng-secrets/.*\.(key|crt)$
    encrypted_suffix: ".enc"
    input_type: "binary"