# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh API credentials secret
apiVersion: v1
kind: Secret
metadata:
    name: indexer-cred
data:
    #ENC[AES256_GCM,data:Mx0FVGJAFD4FFaW+3YtyVLYwCNY19Wp7jQo8R4+B,iv:ZiyMgJ253hlxhG3NvcU9hGZPZzg4/MyZQylfCcaR3O8=,tag:uRU38L+uMLlYNJN7pwI72A==,type:comment]
    username: ENC[AES256_GCM,data:HLGH7wy4SMs=,iv:ooApcgifrSuS1zDTn9XK2TKdKMoH305P8oTV7AnX2IE=,tag:Nc6WjzQfdoaUevQjygo7bg==,type:str]
    #ENC[AES256_GCM,data:13cO7F4o3wQZcdasjJxrsCP5UgYBS3Klb1VHIJcrl0NIek/2Np9f,iv:ebkDFVK7AMW8YJqomtwep7oGNKvlM9Qkph5fcimf5so=,tag:zgKYYrfReZDOgI4b1LbB6Q==,type:comment]
    password: ENC[AES256_GCM,data:TaTqwrH1W+hMI4mxkAx193EESvUgWG+c,iv:M5RtAySSiAgctM/BAZn08lNTYxczuWr2C5gi8nIoVnA=,tag:LhCpD/VvFHwelIy4qM0Xhw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2026-02-18T14:07:12Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wGQFx/ywypOYyVyPTxvRsm6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlhnT1zyWSti6DhSNAgEQgDvoKdsEFwIziyVBmTfHUuIdwEetGC3xRwaxwUBYAL0lXu5oX3O7BBZC3Wn0bmE+Hha8DhFCvXTyBaKd3w==
          aws_profile: ""
    lastmodified: "2026-02-18T14:07:12Z"
    mac: ENC[AES256_GCM,data:3jf1bUUKuvO0dP17Bdh1qzOqyKSMTszAZc2Srzk97n0rzvtefMidOwAXfm9m3GGK7cWCiKc51EZesrPgwN9PCOWoRmH//v9uc/uoFxR/+LS8fEQl+ZsxnLPfsyDmZrPa5RtSHMhSVdyeLWI/LB1M12DveRkwL9/VbiQHoLmJfr4=,iv:PblV0R1m3LdRg85NMRT7tqvCsK3ccoe5uihXXjZKpxs=,tag:njsz6Jvvb4hfc1mmlhhTtA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
