#ENC[AES256_GCM,data:vc7GnPFb2E0mKaymCnI5UkeRFXc2BY14UgF9dF6QTg==,iv:3V1K7LHq9Zwsrok9S450MEkx/rajk7lJ+qF2M3kf6Ig=,tag:jspgPpVpWxta2gPew8nZ+g==,type:comment]
#
#ENC[AES256_GCM,data:PYMmSvzKc6WnnXjjZ0isGbFGJvZSLDBapmcf1ImbbIp/ifHy3up2n31JFO8yaf4gR1GTIH6Ey+Je,iv:om1wWZ2FWi4KkGirCerf1wHFbISigwTma5MTOm1cnW4=,tag:hXN6lpjXM9ZbNkXATpq2Gg==,type:comment]
#ENC[AES256_GCM,data:vxiqaMLuT7n0CCnI03MVZVEN2iDupZwuPE5lSl2zXf7RfBEhnVbcCA0cfWH6aPyMgXAqbzHeQDJmdJc=,iv:N4H/jRs6nwKRyTiOPivpiOyDLBOnFytzaXX2tDH/b1I=,tag:1DgW8Yn1ldDtuinpW8lGSw==,type:comment]
#ENC[AES256_GCM,data:XoroZgsf2slAQcZuTvxX7ioO2S7RVh+IV3j9MC0OjMpW6bCbqyVc7F2zlnB1p60cxe5wtsO/JstVInBm,iv:1eesY10hTCCU5aSC9TLKERLTIFFY8Fi3GnDG7Uf/JK0=,tag:ycMbo9O0FAqSY5cPZXRHpQ==,type:comment]
#ENC[AES256_GCM,data:T3U8EWSVrHjXK2cJ,iv:e4bg/Lu7CUGzVWMpnD/QvSewk/f0QM7q6GmXVaJZ8gY=,tag:tHCT6gITN0hkvrHHg8ksCQ==,type:comment]
#ENC[AES256_GCM,data:ORp6+tsv49Ck5aJinB/g2mR0qjSBanMv4+HsflI=,iv:Nfw6zcEPgyT0hQ9f8Qhke1mGwMOikrid+eW8lyjCmww=,tag:SRb6AXGL+FiceH3ktn9tfg==,type:comment]
apiVersion: ENC[AES256_GCM,data:sic=,iv:EoPihJnXMtE2brBJf1BGiOYeZwygscaPx9uf8eBpBHk=,tag:YrNFgUiI3cF5NnZN5fUBKQ==,type:str]
kind: ENC[AES256_GCM,data:ExFewJrb,iv:4Q27GaTaUth8KqrfaMsEStckrf/VOzULOFlb49JeiAU=,tag:awBE2H5oXnbVrWK6E+Uk3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+ITDN9w+Bfig1tk6,iv:gyTQXLErJmkRWlP4gwtHO52kob941UH5b/3mWV3btmc=,tag:7mbCjeq2NuCbG7Y8VR85rQ==,type:str]
data:
    #ENC[AES256_GCM,data:4COfosznDgp2cHB3qo5TfR0CnptEy5EPzz0V9oBB,iv:U7p46GucstWqx5Gysk6/qXRLripanHCKdGMYZEdJaDc=,tag:K5eHV10E7haYuHTAPcJFxA==,type:comment]
    username: ENC[AES256_GCM,data:Hy76xPmtwTw=,iv:mb3pSp5JimJ9uLV86LmOUuYeiIdONLPUvun4IbNqKoo=,tag:cehdqjhRyWrHoV+A3v4Ozw==,type:str]
    #ENC[AES256_GCM,data:EMhHfFYzanifpJtYdHFIMIc+7tfEUS0IsHUOt0mFcPDym8cW97e+,iv:Pze8l3o8dGo3XgGbPQW9PpcXcW8Wyt/IydZUy+Ap+ew=,tag:+8L1W3DhYJhrn8NyT8jn1Q==,type:comment]
    password: ENC[AES256_GCM,data:t8HPBebbTdrKpwLPaPmihkFKiPl77Bj6,iv:6OYGKIBPzH9636gTCDDXrQyQfeF9HAw4tim+Fy3ZCCI=,tag:kunKJDWV36G512OCbf2Yyg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-14T13:01:47Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wEG6RDZseKtU8Yp7dDCKrx8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlMRNc+MSJJqgw7QuAgEQgDvqf/lXPVzi/BgpgH6ngpA95RCH0klywXSJKNRDc/MTOi3Stum4Oe9/WbhmNsIX4CiRV5fuW99Pbj0TJQ==
          aws_profile: ""
    lastmodified: "2025-11-14T13:01:47Z"
    mac: ENC[AES256_GCM,data:2v2xEKkFMGbRvWr+diCyUpXqZW6TNOuq2Nh9dwLDX0SfAc7cAQkXPuwjRtotqIsrVqlHGd7pGMA2wk8LuUmqiXvNavBmYUibr15bzT0T1Ek4W7DL3GFiaksyrqs33/OSEahSsrtK71sa50aLtGOKqyEomI8lOcVfQNiwgoK6uUc=,iv:/dsKFKXkwmDmFP+fM57I2FwOpjSyKYX8JQcTElsP1GU=,tag:RWlPSJEg+YaAg2O0G3dtHA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
