# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh API credentials secret
apiVersion: v1
kind: Secret
metadata:
    name: indexer-cred
data:
    #ENC[AES256_GCM,data:F4TIEeAu1nVv544dOqLWRovl7HJDLdwY3+m9ld4A,iv:y8yyzN/iy4aMzBb3DuM3wSkyTNzwscoj5T22mAkwu6E=,tag:K6mHDnFZlvpszEAV4+OLww==,type:comment]
    username: ENC[AES256_GCM,data:kkZSCzZKeKU=,iv:zndgdq1kWqElQFOBVQOTcbuWyup2AfFl5fw1RrG8kkc=,tag:qWgBo2vF5s3GOV5guv6m/g==,type:str]
    #ENC[AES256_GCM,data:BFjKZWWiJcOCoe0KQlgCT7CYOWms2shZxCWhotm7GLoMoKHOhE0C,iv:XLb3RigqTcZAj2PAF5TZwHC/Gjlc/tYcCluqRu0nJo4=,tag:K49pOjjevHjj0jy4fxRwiQ==,type:comment]
    password: ENC[AES256_GCM,data:I6UUOO4lWmBZ9F8w97Ih09UO7Fs1hPlp,iv:kBZUtvQNwYpeg02ixR/z7cHRkEaCOSLkuagiLJWYiSU=,tag:WacQgaozQtNhLRewxZ9vYw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:22:02Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wEQbbG9TuYH5r8XfIF3dhe8AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7o11xFlPRFU4vaD1AgEQgDuFxuvErxAh5uLJ94MADtp4nAxvnBD2RjhjrCHMSSPpb9AQknQQN7e3z/ZUQFzBNI58p0hbQ6V6a0BOLQ==
          aws_profile: ""
    lastmodified: "2025-11-19T12:22:02Z"
    mac: ENC[AES256_GCM,data:Bg5MyPQc8gs6l8+fY6T45jL67I9UKiHDk5gD1gYCXBcZFuNzWB1OLh2EuXb1rWTSnRFXhFEv+BDS8MGjzHJcs7RnhbN/m7hVQ81F9+pZdBsKCKgxdTUtqn+H1mUMkFnWGmln99vjta2v3ZRGN8MiPauL5X0fkDuWdz+OVgRA7fI=,iv:CE70RaabpllJVq9s0m0aLGuWlX8GiUY/OtZpC2NbdaU=,tag:augSNcI6fKS4yBBh4B/9uQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
