# Copyright (C) 2022 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh dashboard API credentials secret
apiVersion: v1
kind: Secret
metadata:
    name: m365-cred-secret
data:
    CLIENT_SECRET: ENC[AES256_GCM,data:X9l9HVF/XnCD2Fuslaicjx3w1cn+vE8guZvPpnYDLkFEkQoaqxYXf0d3puCzYPgvFxDyL1QNqY8=,iv:Kiuj9nPyqY/pbhrt26Zk0VvECaoseF9bwHN2yjw+cfE=,tag:6h0jefzKYwlzB0UQnHPRQQ==,type:str]
    TENANT_ID: ENC[AES256_GCM,data:DYAilCgXMxgQpiws+ShESFCaFG1ODXcnRSDD7Kf4zlCpFrZkHYDKfCaGiA/bDEqH,iv:No1LYztt4UvA4J04joFk/IvrgURsQb6tEeMMlusW0rc=,tag:y+iD+4yu9y1gTTtJEGMgJw==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:XAa0q2ml4AYh36nhaShjbaN33TqGB6gXZix9Kby36kh+amE1GHDBLXVpUXRVyXor,iv:nuhSPcBPtrb8jmUiTdtawSbGvMPPUQm+w4AWuj2C/Mw=,tag:IYMm5vz3M0FHVfbGuIbr5g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2026-02-18T14:07:11Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wFfsLmYWrutX+BUUj2llFpXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcka50iOj6tf40jWcAgEQgDt+hT//1gXpUF9yEYtpEYAMy4PDlCv2csmMsy3Ny5K/MDNQRoNR2rmAcD3QUfknWF1E+OyGfdzNt9ZghQ==
          aws_profile: ""
    lastmodified: "2026-02-18T14:07:12Z"
    mac: ENC[AES256_GCM,data:49YTfcTfHKjOnfYlzs9sa+42waw9tb+Ii/PeYdYiGxyvIF8emK+MbyFXRHm8v8M2It3FF+1r32n6r25unviJtIgz9X+Pl8EAw9IDH/xHJ5w+7lsu4wJl6iUNymd5AYk/MSpWjMxeZlxLKOWAe1BoUPd5GwmWL1+WINj6AybmpDE=,iv:SvsznpsMoGCZBiCQG/yjeso4Xv7kFjrl3Tcz1hlSZYY=,tag:RNKyXvh5q4wQYQWNrSdYLg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
