# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh cluster key secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-cluster-key
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:ik0ptJ0B1KW+2340GAfaA+nH1oe6SYcm2lmmh2CNIO7sJVCUOHD65EDbdUegozJW/qYgD8pAc5BG,iv:ifPGTgjU/7X/ku783P4OpbffHmiR5nrQbLagdyyFlGw=,tag:bo5dBMu3LnMLAjYI7kCcUQ==,type:comment]
    key: ENC[AES256_GCM,data:iY0NnrlPX+E08D7XUnTNn0cPJTLAKo2H/DJ4/RfpCXlGsmhdAFP28oB8T/8=,iv:SgAS/wHQGOhC/GuzgnwGGP7gQBJDNxOWKCv99BPsOBw=,tag:GEFJWPbRVmOWhsxDiDkocw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-12-05T14:07:38Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHLL7tTIYMDBrAgvH+XobHlAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMtWZmm16yD6roQfQnAgEQgDuXmoXiIF36+oPjmCpY+V9OYmt6z4253y4/PxtNngd4qx9IyXXP7sR4g8XqFB29bLkT6BshZ5d+BBvMcg==
          aws_profile: ""
    lastmodified: "2025-12-05T14:07:39Z"
    mac: ENC[AES256_GCM,data:VyWrKtSgOAvIWdgXLUAxYDbQkQLYjLbKsEg0Qj8NWbWKQdDYDdV3kZOVbcuj1ZEB/nNGpGUal6qMcKDL6hXjRGwbrSsolcynl9bK8EetJaaXtEkCBWO0cxz7X+FeocYF59a0LpgBbR3dvAcDATny7yfdI+mbLIgIVKFFhFCxza4=,iv:9l+VuCdmbYScClJmEEtvxPZigwTpPlJh53CO+sJiu/c=,tag:5D0QgD5sCLf37knjcUeYXA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
