# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh API credentials secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-api-cred
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:hnZVhGA3Tuh55N5D6EaFNaT9/GZiA3Yfn+WzIAMnhJQrHg==,iv:mZ/Ke7FwMDu96UmtBurWFeDEv486RtNbrABJ8nZvGGk=,tag:Pvta8BUFOg14Evh5ITDmYg==,type:comment]
    username: ENC[AES256_GCM,data:D5cyhxwam2W3FUAR,iv:/RaakapEgSAvPVTBsIOgdNhDitJu8jLSh5E8WyPaMZE=,tag:C0XcXGFgpZAENEnW/4RxXg==,type:str]
    #ENC[AES256_GCM,data:0r0MAsq8+/RVOyLQdBiHUQ==,iv:S3sU7vxBnPSQD6bgsUtTtyJYXOIAHh0EMOgnA4H29Gw=,tag:8DWrjZ4w/x3xHVgSF4RVsQ==,type:comment]
    password: ENC[AES256_GCM,data:IwC2p9yTcwAb2tbwfGrVY8eu9Avaj3IwEvT0eE+f4CQXnVPmfXywMA==,iv:AyNrj8UJ9CMbWzt2agsyPVZqNxPGyfx3JK8OR5XLxrc=,tag:cjSC+3DTNjFrbN2hb1+HQQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:22:01Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHDBoCt1E3/z/MlWYgnaHgaAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqMn+T7j74lpheFqtAgEQgDsgt97VZ1ZazFj9D8aWfwDFzADhZFv7fn9MFhLBnNpPGrEHuvbt9CUo8anTkEFFb228Kt1PZTjF/rmVRQ==
          aws_profile: ""
    lastmodified: "2025-11-19T12:22:02Z"
    mac: ENC[AES256_GCM,data:nc9cNUUvC8y5WrPG34cpnl3yWFnGdp/22qm/ktbjbgAhPapfbNJQwYgUMvReB48f6O4T2TRVh6CpdmOAEyfjVdghTUk8zY7XScByi8r68Bn8zUyt67il6S/DVRD1JjU+17uZ86ZJfxrnjAHxuce8vxQGlyPkhUFMQwaRq4DwSL0=,iv:j/gnHri/NVwshxVEpqGY4kQIsRVcvpzbs6vPwEs9QqQ=,tag:zHEt+zNluooC1yRYgN/DMw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
