# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh API credentials secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-api-cred
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:hw3D+/xIva0+mAPV+Nj/nMDkMFCscZoLMRWCzMp3LiTyvQ==,iv:yMSCM6K4P8F/yE2fdVbzcWFVi4jMxl5DtHizODdZNC0=,tag:IIlzgJD77bnB57Hn11+C2A==,type:comment]
    username: ENC[AES256_GCM,data:FeGyjj9MBG4onHwM,iv:Gqoc7MVjkoWm1hpUjMdUhfKP1Aoah1hXBej0MvY2A2Q=,tag:Gj0MWZ0f0gX9kcNsk8FY7w==,type:str]
    #ENC[AES256_GCM,data:KDaufqpo5CTCzQJ9vYb2j8h90WaRFdnvh4D+tYpRjBafFND20Gf/zJY=,iv:gFyhnuP2Zeuv4g5LqDpZDUB4Jhv6BzwFv7KIon1kDvU=,tag:wMcUk06pd+PAKBkwMRZduQ==,type:comment]
    password: ENC[AES256_GCM,data:FJZgklJcFRByFfngySQ+36taU6JKypBl,iv:eQnTVsHlEkLFnENOYJPxAYAQ9n8f6xN9aZM3otQI7nY=,tag:yJ+dkHGAImd6wJecS8ImOA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2026-02-18T14:07:10Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wFVWmBcc/UXhRGWwzafxIFRAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFrCnukygrUlT1idiAgEQgDsmVM5AtR25M9p9CM/Wdk6wqEpgEKe7wQWPhqgXEJtCRg7bOVxxu26k9V60QROip6yZKcuVwx8wZjtNOQ==
          aws_profile: ""
    lastmodified: "2026-02-18T14:07:11Z"
    mac: ENC[AES256_GCM,data:CH9+eG8dFnBD6Qr5A5xh4uGrTBJkbL7ZPHUBvyIPmgMQJ18yUCuUkviHuQsyeXNPrRXU2snIb1nWil/NA9z0nGiUvmuNf9ixskrayBBrrrG2F8kU6IjQuOQ9kSgoUT3p6mvw43Ld5r3by1GjGFPRaQX6TMG5bDva7DB1XBdrafI=,iv:S44s4zEnQOBnL+T/vR0qKwyBVZdwD8F3LMcZ2x6HTKg=,tag:2gkm8bDpwEeHrl95WFklpw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
