# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh authd password secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-authd-pass
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:Pdc94MsAIM18Kmn5cS3hGYDG3dIxelxjlt7rGhtV69At,iv:vEuZr4ejhRdqxo1dS6OJ9jILVlG6aBcz8LGoidr4T90=,tag:3nvXmeNC/E3Giry6LAlAcg==,type:comment]
    authd.pass: ENC[AES256_GCM,data:5PpMsqOOXjYub8xg,iv:UmFZVrvTQD/V9CywbhV/y4ZDypBKlYzqESkwziWtSK4=,tag:1g073jwX8SFWuHBgkTO+5w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-12-05T14:07:35Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHkz6lxZEJBjchG7CwmC1owAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMLk1vkAJcOxwf+5OjAgEQgDvRaYLb16ZzIgI+NCSGJnPiLp/DdYZJCMJ801F0joCXsaB/iPKBI6e+xb2iJ9ltAil7gb2AbqMMzCpg3w==
          aws_profile: ""
    lastmodified: "2025-12-05T14:07:35Z"
    mac: ENC[AES256_GCM,data:m+sY2wgxoIenmuQt8ZlzeMsAwkaj9DFvQHHAAUbFxgrN88/9pLx14JkTs3Ym/KBcXtahP8QymYlzUDxvSHGEARoR4LW3WLxBIgo38NgZPHyz/8kQhJxOaHhL+QbpzCnG+HTtjKbcpuKGSy7YUMgfOpitskn7z/7HNl07viUM9P4=,iv:qnL/hFauIZAU50tBKoBlaYz/o7tb/afXJZ8DM2CCfcE=,tag:c+PIOndhy9EmaiqkDOeMMQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
