apiVersion: v1
kind: Secret
metadata:
    name: wazuh-s3-creds
    namespace: wazuh
type: Opaque
data:
    access_key_id: ENC[AES256_GCM,data:bsSS+a8SmyU/vOMDjvbolGdsZgZd1Ws36v3TBA==,iv:Ecw8CBgRyTnroCnWYG44bQlkC+A3lC6hqd4B/g/W6a4=,tag:bK6/Nqf1jELtwcIZjxYBpg==,type:str]
    secret_access_key: ENC[AES256_GCM,data:WlatNVM5GINoylc3hubOvKPDloTDApmlMuve/rJfD1Q/aJXP7m1EGeO3YEcS9wGFAYT8UrXcIAs=,iv:t81Puo3eU1DEWNrOYQTdT/emb/sOXaa6mxSyAMp3kos=,tag:3dJvolebDYBy1VO1lUdBZw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-18T13:26:10Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wGZZ5mB/iw6UQ3GvuXo71fTAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMS6xM81xpL0y+8vzmAgEQgDtHjgDobGvY29vFerWBpeE2+lzmNPdXuTxhv86FJZ4sdGDmalzaMQTSG2IB4XsQo66ZXNPRebbWLy98Kg==
          aws_profile: ""
    lastmodified: "2025-11-18T13:26:10Z"
    mac: ENC[AES256_GCM,data:e8sHKSYuI4zVKmXuBhRS7/pu0DwM1aTOnGyY+1iFdw/bqu4TFKmMWaifoazMk1JdUVMce80bjoAcM7G/xV39+HACYRXk/++uBCpMh6SUc03nopbaw35kDN/IgdSrzBmW4NmMCh8kbn9BxfpDXfd/CGyNF+fxIIzBEYHnqPb4B54=,iv:FSKYajO4qUvOwM7lUX0sI9Am5ff1M0H6lEdFLGvrf3E=,tag:aP2nkK9B/PfKnVDLJfDmkA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
