# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh cluster key secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-cluster-key
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:azsCePbJAZQAdDJQteNE6dDIU2NtK9G0tpFH51oyNyp83cYl27iiA90MkZvkSzKk/d34Z1/Uo8GW,iv:LIAayVzaruKBTTNn00sDxINO+VyCbocW0X4uc2r1jUk=,tag:kRDbsnYIa1kcKlhUp5B9VA==,type:comment]
    key: ENC[AES256_GCM,data:Kw/46/GPbNgVmStt18+K1oyqE5+lguFrSIJpU/bfcfI0EyB8YK6NhidkSQM=,iv:cVnJmsEFYSm+ED6Vc5J7nTnNfeljWzBzJA0vF222+AM=,tag:W0IgrGa/Caj/6uHqt/mRIg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-18T13:26:10Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wGPFe5IHhLPzSiEeuOgsbYuAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFuzhRP96aHfqhOrWAgEQgDvvDH7fu+7ud5Ybh0YRGL4XAnkDIRFLlH+4PfQ5TKHF8y36C8a8K0HOIfP4KyLs70cSko06etlrWyXsYQ==
          aws_profile: ""
    lastmodified: "2025-11-18T13:26:11Z"
    mac: ENC[AES256_GCM,data:7nUMsiE70ZFxzdq0PF0CLZVsNi9YJwYYbTtZP0iOUfuDTpx+B0/jGgZRw8Jws6DCqprFR+WH9HN9nnyDzh84DZGKqUC8pr4qmDgt8XkqFag5X5C5zS6OtCnMUaYjWjJckMc4ueXLP14kOMlJ9U2SajoVcZQiVKO/4ajMa8ZZii8=,iv:pdj5VDxWUJuzPpkLmyfrrSY00lBhEx0ssixWAM2BcGU=,tag:ZQeuWGn2KTwxz2l9ZCGk5A==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
