apiVersion: v1
kind: Secret
metadata:
    name: gmail-smtp
    namespace: wazuh
data:
    username: ENC[AES256_GCM,data:dOK1oWeXbzHpNb1GpH0B3QbCrASnUFPIFzt5ROZnm6hP2u0b,iv:fMxpZ6xYFQoLqhbv0NB3tNfHpRt6JyHRw5OywuqQeTg=,tag:lOZyAg2U6DI2ggAZz1Vp/g==,type:str]
    password: ENC[AES256_GCM,data:mtBoOrNVgnydKT5fcemQ8PwCcGfIyqoQ,iv:7gQbb+QiO/2ZBl+MgFBCPiaaOsYHgagOttrB5c/3Mj8=,tag:qN+MbkPmhL1YKoq26mKt1w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2026-02-20T13:32:08Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wE9xKlNT31qHQIXX4pn8U+SAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKx5UJwuy6YT8+VgDAgEQgDvz9BF1OrdiJ0cdmsPDf14WwoObsKpeKaccUAVeAEQdEXW2GhmQtJh7Yi63sdMXJxzkHS6i98M2KXj5Gw==
          aws_profile: ""
    lastmodified: "2026-02-20T13:32:09Z"
    mac: ENC[AES256_GCM,data:f9/B9ezOt43oDNZ+dxXexjZ5iAZlMXDd0Fqdto7nDTnd2YsZFGCz/CUILS6+8iO02/Qh4xsm6yIKJjcKIQmERCu0VnlliZg6cimsqU74syTjdqt5/lTVU830XkR3Ng4BFwZtA4nzDRBS2KeWW+9hWrzJ9trwDC8HYqmH/VXf9cU=,iv:gekBHr1crSzfp5O7LrnoObUmZ5SxL4KNbCdGIAa/c1o=,tag:+Ea4jtoXWADkQbIl36qYKA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
