# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh authd password secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-authd-pass
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:Vl3hpQTOgNKLxBesPclATDgjDCh9HHZIRJbqoDzAO+so,iv:e4Hmc+s2QkB3pofE8BuL0U4HVhDC8KxNjf+iHQdcs7w=,tag:08wcvzqwC0hb9t7lF7m4jQ==,type:comment]
    authd.pass: ENC[AES256_GCM,data:RR7C0oyByxLwnkb0,iv:Aivokdv0AWFrgBKIiko4waQb+VeL4BgjN3Hr9HjkBAk=,tag:Ced1ERFZ//WRivtEaqRLmQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:26:33Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wEd3ShgyfabOZ0SjvWHH1eqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGboMUH6wfMpXqsWJAgEQgDvx+hvP1QRmay1xKdI2mfZpTYk4Kmam7fPB6fIE41xvyCjdmOZ26ikB/29OYGHfBzoiyRrxTaULHdjCeQ==
          aws_profile: ""
    lastmodified: "2025-11-19T12:26:34Z"
    mac: ENC[AES256_GCM,data:txfrEuUFW0dR/kzT84Yjy9HN+gKuFkXt95ittTZCelyXv49nkeMxWKJMK5BRLQKEI8mBndQqumJYg9pq7kTgBSFFlWz0qQUE2nW2+CHhTqbkDvzdnEUM3ll9W2oloTRmUiDk7QMqzDJBG798OdnX6aaPM49+YoFda+P1ZjOqqDg=,iv:n7KlgH36xo8nqdElxNElWinZDHxi8UvQs85mX7Kj1cQ=,tag:oUBn4/FNEaBnP9eq7kZKbA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
