apiVersion: v1
kind: Secret
metadata:
    name: wazuh-s3-creds
    namespace: wazuh
type: Opaque
data:
    access_key_id: ENC[AES256_GCM,data:AGkX8fW8WxabThoQA7ED0VlhtBrrQQF6Z4f7tw==,iv:vyTj0rZbkp0T3ZRVYmV+lDsr+x0gQLWLmrVhYXNv0dk=,tag:fOO+nS3NaLQo/PfUHVIuzQ==,type:str]
    secret_access_key: ENC[AES256_GCM,data:jrR9dLrijucxINbS9JOfIMbiIzgKM9xVdWE6TLu0QqdVJDh2MXTLRqxO1Q/0HV5474+azaegLWc=,iv:akQellmQ+aHxvqk34+fl9Mhr1JETLGJmd2I/a8Ow/hw=,tag:APodg2Cff3FZiWpcThhCZA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:22:03Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wFbj576QECHo6cgEh6nw4pyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdLQmpwkMpU713IzuAgEQgDvi+GMDnPqtj3daCUIQVgcjeGR9Oyr3jPGERSxP8lYPKFaTV7qbqg4+OslcGESk8Z/2y3Sew+Qhxj+iqg==
          aws_profile: ""
    lastmodified: "2025-11-19T12:22:03Z"
    mac: ENC[AES256_GCM,data:oS6rZgwbnNDNizgNF69s89wXIDlH12T9ujrE/jLa7f/RVwbbvbsiulE4vgaPlvlGBpuMzqKUW7DmSsOVVsNW+EZ/oTHwWmwCLkPBX/hTqo3K3z5SecIKzDorviQb2Iv98nVzORnzyrpFoNN6PobGqAc12enZJMoBw1IUEtwH+xg=,iv:zLlIBI1usqDc51g1Uzt+TujfyXy1dbob/vLKdR0tPCM=,tag:6LnMpSh5NtQTKNX+KTWurg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
