# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.
# Wazuh authd password secret
apiVersion: v1
kind: Secret
metadata:
    name: wazuh-authd-pass
    namespace: wazuh
data:
    #ENC[AES256_GCM,data:O0fdVpFiejth5OavXan8ZGa6EGHowjOBJOesWXF9Q+iY,iv:Lw62JgeBhzDgMM84geLiKmnHpTSxf0cmEY15gZ42nnA=,tag:EPc6hwyI64ukaeLcoLRkEw==,type:comment]
    authd.pass: ENC[AES256_GCM,data:kHy4P2VYJ20MC/ia,iv:FXuY0rsZX/rduZQYHLgmtQ8dz7FmRSzmsoKrg8nNKGs=,tag:z8hcprpbZIHb3vExEygJDw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:21:58Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wE+ligf0N0PwuBLEzpoOQldAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMSbq6nZQ+TOIE1qgWAgEQgDvrVRSVmjA5GljCnpk1aiwq9AuZfNYZtDgtfIQFTf8fpAEOHrNPhK88VEIenjfydD0siltz7RfNOEK8Mw==
          aws_profile: ""
    lastmodified: "2025-11-19T12:21:59Z"
    mac: ENC[AES256_GCM,data:LV6THwwM3zBPDec1aq5lEGJX1NGcYiko0/Z1ILWMKeuoi3sVB+lxiv6WzBF0M8rX1lfIK/JCRPTeEOCyP2zHCJE5FQSAsHaFE9FUFuBHnQWLeP6rzTLvJtASIyOBqrfIHMafDUTrfyo/j2ibskEPwNiZ69QBTDVh68r7rgctdfY=,iv:CAM8irihHWMfIf34cRgf1y2doVlCrnCGBDp+hz1tqCY=,tag:LJewA8l3rp31mbFrhS+KeA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
