apiVersion: v1
kind: Secret
metadata:
    name: wazuh-s3-creds
    namespace: wazuh
type: Opaque
data:
    access_key_id: ENC[AES256_GCM,data:VIlInpMxSeJLUyvRTqu4QmoCUT/9O2yWDS9h7Q==,iv:u2DjxZu2e/cJM+pRJOGWSoOgatUImiBSSazO4189bt4=,tag:vMPZHyjkGdg7gMX5uov+aw==,type:str]
    secret_access_key: ENC[AES256_GCM,data:muVt2+Lt9d19Ph4Wry7V+vqN/+6eBhGH5TYszFBaa0TcCH4hBOiG23snQ18ra/V1jA6M9skCxEU=,iv:jDsN4CzaV+riO3TSGCOlhdTsGH7wLHx9yBX/U52EJYY=,tag:35TPIKkVTLTYZmcbmVl+mQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:26:36Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHQUitRtt9sOVYvB4RugR9aAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMw7aFVib3fqMpDs9gAgEQgDunvfdKg2aIZWe6IiFbhpvbr6DKlhEQeCPfIg0UWc5QNfDDzjDVOQQxLpxGfcSiK/8D2s41tBEu71kvig==
          aws_profile: ""
    lastmodified: "2025-11-19T12:26:36Z"
    mac: ENC[AES256_GCM,data:phV/0U2fha4DGXnZ/xd/Frgjz4/usOJKObdQMCxz0RnZhuhIbmbVYimoajOFt+jNBpVfgTQ9OSM/tWLa2gQM91aK1wfG3PQJlK2kXPo7MJbUq13fiw1fU+fX5ukSA7wO01tk8D+cKTIdKuLuXhu1sDurb3B1h9FCkSp1PQgf/6g=,iv:ZQUwdvEjzPLMe9OzSLTdceWhUwF4k1D8ZAYV2STDv8Q=,tag:X8clOI3uoM0yfMsAXJ81AA==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
