apiVersion: v1
kind: Secret
metadata:
    name: google-chat-webhook
    namespace: wazuh
type: Opaque
stringData:
    url: https://chat.googleapis.com/v1/spaces/AAQADjkyoiw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=dmhH1PVLvHUKc5Zw1pG8qP8TsrvG3GayK4OKC3508zc
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-18T13:26:05Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHCbnE9kyqkRhVeO+9GGzq4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMH0pdgMkL6JDtlfklAgEQgDuLvuMNyUvWW43YGPyypxS5HKvVNhbjpZTUqGo4eRFD6f/VJDrslaB4ad/HKuX8Na42X3A1nNRBWH+GKw==
          aws_profile: ""
    lastmodified: "2025-11-18T13:26:06Z"
    mac: ENC[AES256_GCM,data:h07CCeG1zSi+NR7JtKC+/kXJtZS0YBCqO1mfA1l1FIYhkm0cqJBNhd4jNzyn6QT2F9+iGOwP7LqYF5i6/tOH16/y6sXdeFCCCwjuY722YKQxbMWIRAaGcmqOCSNsPe5NNIoWrX3mhYYquXKjqgqqcRqastFkkr5hN/m0S6IYrYs=,iv:gnF+5FcHfoM9WlppSxstnJAZMHDUTVKZweDT0c0ARk8=,tag:YJVgZXjA3n81XfJFsaolhQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
