apiVersion: v1
kind: Secret
metadata:
    name: google-chat-webhook
    namespace: wazuh
type: Opaque
stringData:
    url: https://chat.googleapis.com/v1/spaces/AAQADjkyoiw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=dmhH1PVLvHUKc5Zw1pG8qP8TsrvG3GayK4OKC3508zc
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-19T12:21:57Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHVjZs7NvMRcp6Bz8qekxx1AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMne82H+eCvsZGjsFeAgEQgDu0doPSSqUFXPUldS+Ax53YjmbjxSLn6mlSZ0tF1m0MsclqAHTylNF+V/N148ogfO54zh4wFX5xujC3zg==
          aws_profile: ""
    lastmodified: "2025-11-19T12:21:58Z"
    mac: ENC[AES256_GCM,data:2i/Fg78fOoutp5LS2DqrJuZdz5aXVDubhxaLkn0Ug4YO3ZjeKMX2kwM8lMrSb4nP4HBN/BPyqaHfxlxkjOwGo2zpah0LpCrvl0gBxZIbsbE+JMTxPTPW49wSmBl0/oWEJjeE13Qjptq70INB/pjJ/LaW68UTgapLl6Q24QETk7U=,iv:Eln7UxjT5YHGBN9VoW6HGwQhJmIqDibIMXodCCKAMHk=,tag:GPrQGGazq3CZMvPL7FAKQg==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
