apiVersion: v1
kind: Secret
metadata:
    name: google-chat-webhook
    namespace: wazuh
type: Opaque
stringData:
    url: https://chat.googleapis.com/v1/spaces/AAQADjkyoiw/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=dmhH1PVLvHUKc5Zw1pG8qP8TsrvG3GayK4OKC3508zc
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2026-02-18T14:07:07Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHKBBZD3VLI60J9DaYR8VVXAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMLGPgNPnvMzR/BYmdAgEQgDtufzcTxyRxVl5nN5ASquq8j1x5IKvwxZsfI/hai2rffbzPAd6ASWqvAYDmfG9mv/y8pl12NkXlvWXK1g==
          aws_profile: ""
    lastmodified: "2026-02-18T14:07:08Z"
    mac: ENC[AES256_GCM,data:jpUIKAyTXZVo8ve91gdGwNGsV0EO1tE8xWT3L4Lb5YxJyksPFAO7W0Ve6kZz/+mslHf1ac9btJeisqt1LOF1RhyQu311IZ6GsNJ1MdkBRBuyMzGSX9P2/8bXByc20NvT0pqmpi2dmbTSWsIgTfTH7t4wzQM2Lx/V86Zj9LYlbIE=,iv:ZIoec5giDhd9Xv7It3vBzpYGrfRYlbad9tdDdFNL9Eo=,tag:PWuy5xoMVuzXVxxasg8lRQ==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
