apiVersion: v1
kind: Secret
metadata:
    name: supabase-credentials
    namespace: wazuh
type: Opaque
stringData:
    url: https://cwhzzadfxhouvvxzmckp.supabase.co
    service_role_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3aHp6YWRmeGhvdXZ2eHptY2twIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODY0NDExMiwiZXhwIjoyMDk0MjIwMTEyfQ.1OOcb1bTdFn0k8VorDuoMHDdwAqOZTswscWAfy_fY98
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2026-06-22T13:02:14Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wGa1pfi+bgT2jCNc+deL+raAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMD+O7F6+WrF9aLyj0AgEQgDuScpAgN9Nit3cnAko2OUVTNb/ibsuPuADlapv70u3Aj7prYPWFiQiZMqQxHPnxtClbKukNSzBdQlrR4g==
          aws_profile: ""
    lastmodified: "2026-06-22T13:02:14Z"
    mac: ENC[AES256_GCM,data:qZGo92r8+4iGFPukt3mMI1QWteiNHzokQaCDXtzatB/4rPs96o6ilevOj5fYzpH/gKfofYd0kgzKt9YJ6OnjeSdmWWdJjMMFdIHqC6DRB29fwTl7UhgP3znj+wUggS0myRJM5iKQj9pcr2K3mRjQK0bR7ovgqG9MdLjDTYvEEGA=,iv:ihoRJWfQq2ggqroXOW7qWwGgivjXlNNpYls/uW5wjLQ=,tag:ld9ZZw/IaKYAOpzlxd+62g==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
