apiVersion: ENC[AES256_GCM,data:yzk=,iv:YZyc5d1M1VvZsR8hWXXv8pX8W3jKtSONsyuaqsChU0U=,tag:uQh2CS3dSplHTfeoda+Fzg==,type:str]
kind: ENC[AES256_GCM,data:FEh9mrvs,iv:RDDBve105rNQ7ZfZl4VuH9DrrTvWQMjRf1WLVx5zs0Y=,tag:G8SOdrpFPbt+VZ3lUTul5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UDmLkzJs4xbAEvir1eskTI9x432k,iv:O0Ian315T+/MI6NA+CvCHH++YJDCXDIQMmB5c3s6W3A=,tag:saz0EfsHLYlVtw9FNlyCEA==,type:str]
    namespace: ENC[AES256_GCM,data:cpKP0Jg=,iv:bIpdMRyb6+dFluVK61EESmMds/DBUeH3ScD1ARR9e4s=,tag:mFL/AegHYhXbaqHlKXqvJw==,type:str]
type: ENC[AES256_GCM,data:I7eyNSYw,iv:nsr+tcbMPL/fb8MPRyhMZxHg92Y+yQb4WCZdYqLcIXg=,tag:xpjpv3wJDBN8i4dIoR8j2g==,type:str]
stringData:
    user: ENC[AES256_GCM,data:03onr52T+Esw,iv:cOiv9SmMB1en604MA20NliHJVLmbuzdQ984Ur74xzy4=,tag:2ne9Wq9KFnKFmnxXHJOuwg==,type:str]
    password: ENC[AES256_GCM,data:4vYFmTviunaCAlw8hQX26Q==,iv:xeSxQX6dOZDO0aeYvwEk8vaidx+NftWTVGzJK2r0jug=,tag:4NVkZIxfeagS+Ecyu8zZWw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-14T13:01:43Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wFSIL4cz47Xa3n1Ni7A69oDAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMm/nLUA3mzho3NEv6AgEQgDsy174ExKYpIYNpph1TL++re6eXO/M9+WsL8sGsm1UJ6XDIiR8kE6byhZj/WVf2BrIwu5TaxbH1irYtZQ==
          aws_profile: ""
    lastmodified: "2025-11-14T13:01:44Z"
    mac: ENC[AES256_GCM,data:DzlFsF/u0O2iQKbyHRbSG0F4hciKU/Qr3LVDso2NfzNN96gMOtSCtMb/pVXXDtHwSMGdQ/0tg7Tt4dVALekSgHUJW9Bo/xAKjxUmBI1u2NF2uxHXix5khTC29vm19IbSjBbCM8G4igt//6ouYQiovmxXu1AKu6/rLVYb0Mi1Uvk=,iv:mc2m8sv8fwXzcv4RdMk/hUuJeSW3Y6kxGXD5ExednLw=,tag:fem2Q6KgI0/bW5o8l94kLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
