apiVersion: v1
kind: Secret
metadata:
    name: wazuh-api-credentials
    namespace: wazuh
type: Opaque
stringData:
    user: wazuh-wui
    # MAKE SURE TO UPDATE THIS VALUE ON AWS PARAMETER STORE TOO
    password: KNH18JBqwxCiU5EsahTQCBz5YUY=
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-12-05T14:07:34Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wHHpQM1RLEtzsB7VZgXlgaSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHB3cbGVVKt4hCEY3AgEQgDtoVeNXUKpBd/YToOxAya7nWcBFMAMCxNkx9j9Uf8ezdP6xO7r1h2H53sjldC5LtXK1QPOuPRDaW1p6Sw==
          aws_profile: ""
    lastmodified: "2025-12-05T14:07:35Z"
    mac: ENC[AES256_GCM,data:NVF6udsmQ0Q1NosMZNwmt20k5+NXQdIL43EFFt1k2XQYgCs6fLLp4JkDOHdnF3GGYdvj9b2olN0S3zq/n5MvHQwmJ7T1yH5DkRl0OXVDl4mwcJ6P5QlbWrxpePPZ8vpV+EQWbZAmI7ls13MoJ/CaX4clJYrKE7Vy+kjmF+eVbb4=,iv:Rb96hkmWhKXQU1BB8najDhrgeuiD88CZVYxj9WVgd6s=,tag:UdSe09yKMKmQtXbXH1GUgw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
