apiVersion: v1
kind: Secret
metadata:
    name: wazuh-api-credentials
    namespace: wazuh
type: Opaque
stringData:
    user: wazuh-wui
    password: MyS3cr37P450r.*-
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:590183765660:key/5895808f-d841-4d2e-87b4-d330e30c1ece
          created_at: "2025-11-18T13:26:06Z"
          enc: AQICAHgc13Alb0YKB/uUIPrFU9WGTiO07sTuMvROyHt20jIm8wGXCxiFRWPMWT5v9UIljsMdAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgyI8WnHkMswl6C7aAgEQgDvFSOXHa0O3qgOSZqNY89Uv8ZDsx76szlMtocHKa1PmUub7r5OwGu8QkdzQxzY1HZuzpz/URp6SrDhrMw==
          aws_profile: ""
    lastmodified: "2025-11-18T13:26:06Z"
    mac: ENC[AES256_GCM,data:MefSrXRqf2zdWHgaSzfvk4FzpfbGs/N+QAUAWePsjYLfROF0VBGQsW7hQx/GrOt1i+9tJdAQB3z+cx62UgxAsuBnfXcoyqnAVraX75MK0hXaD+HcUAlDa8kTMAAHLklfC+UvWmm/gInLpa/uUVJ1fff0cv6fgH3x1IEGHGcuX1Q=,iv:fvkbK/GtfalHGmPYpNwsUtG+sqXEkRwVPfypyMnOvE4=,tag:aF8/OESO4VxS7X/9VOIEnw==,type:str]
    encrypted_regex: ^(data)$
    version: 3.11.0
