apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypointsh
  namespace: wazuh
data:
  entrypoint.sh: |
    #!/bin/bash
    cp -r /wazuh-config-mount/integrations/custom-n8n.py /var/ossec/integrations/n8n-cm.py
    cp -r /wazuh-config-mount/integrations/custom-n8n /var/ossec/integrations/n8n-cm
    chown root:wazuh /var/ossec/integrations/n8n-cm.py
    chown root:wazuh /var/ossec/integrations/n8n-cm
    chmod 750 /var/ossec/integrations/n8n-cm.py
    chmod 750 /var/ossec/integrations/n8n-cm
    chown wazuh:wazuh /var/ossec/etc/decoders/sentinelone_decoders.xml
    chmod 660 /var/ossec/etc/decoders/sentinelone_decoders.xml
    