apiVersion: v1
kind: ConfigMap
metadata:
  name: local-rules-configmap
  namespace: wazuh 
data:
  local_rules.xml: |                                                 
    <!-- Local rules for RISE BROADBAND-->
    <!-- Local rules for RISE BROADBAND-->
    <!-- Local rules for RISE BROADBAND-->




    <!-- Modify it at your will. -->
    <!-- Copyright (C) 2015, Wazuh Inc. -->

    <!-- Example -->
    <group name="local,syslog,sshd,">

      <!--
      Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
      -->
      <rule id="100001" level="5">
        <if_sid>5716</if_sid>
        <srcip>1.1.1.1</srcip>
        <description>sshd: authentication failed from IP 1.1.1.1.</description>
        <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
      </rule>

      <rule id="510" level="0" overwrite="yes">
        <description>Suppress rootcheck alert for /dev/termination-log</description>
      </rule>

    </group>

    <group name="office365">
      <rule id="100002" level="0">
        <if_sid>91556</if_sid>
        <field name="office365.DeliveryAction" type="osregex">Blocked|DeliveredAsSpam</field>
        <options>no_full_log</options>
        <description>Drop event: Office 365 Phishing and malware events from Exchange Online Protection and Microsoft Defender for Office 365 (excluding blocked or delivered as spam).</description>
      </rule>

      <rule id="100003" level="0">
        <if_sid>91556</if_sid>
        <field name="office365.LatestDeliveryLocation" type="osregex">Quarantine|JunkEmail</field>
        <options>no_full_log</options>
        <description>Drop if LatestDeliveryLocation is Quarantine/JunkEmail</description>
      </rule>

      <rule id="100004" level="0">
        <if_sid>91556</if_sid>
        <field name="office365.P2Sender" type="osregex">workflow@jabbroadband.local|dal1-imap.risebroadband.com|root@dal-rf02.jabbroadband.local</field>
        <options>no_full_log</options>
        <description>Drop event: Office 365 Phishing and malware events from Exchange Online Protection and Microsoft Defender for Office 365 (excluding internal imap servers of risebroadband).</description>
      </rule>

      <rule id="100005" level="0">
        <if_sid>91556</if_sid>
        <field name="office365.Recipients" type="osregex">jjacobs@jabbroadband.mail.onmicrosoft.com|kdegnan@jabbroadband.mail.onmicrosoft.com|dlivingston@jabbroadband.mail.onmicrosoft.com|mmessmer@jabbroadband.mail.onmicrosoft.com|zlewis@jabbroadband.mail.onmicrosoft.com|mmillar@jabbroadband.mail.onmicrosoft.com</field>
        <options>no_full_log</options>
        <description>Drop event: Office 365 Phishing and malware events from Exchange Online Protection and Microsoft Defender for Office 365 (excluding obsolete accounts).</description>
      </rule>

      <rule id="100006" level="0">
        <if_sid>91556</if_sid>
        <field name="office365.PolicyAction" type="osregex">MoveToJmf</field>
        <options>no_full_log</options>
        <description>Drop if PolicyAction is MoveToJmf</description>
      </rule>      
    </group>