name: Verify Secrets

on:
  push:
    branches:
      - main-production
  pull_request:
    branches:
      - main-production

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SOPS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SOPS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies (SOPS + yq + jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          # Install SOPS v3.11.0
          curl -LO https://github.com/getsops/sops/releases/download/v3.11.0/sops-v3.11.0.linux.amd64
          sudo mv sops-v3.11.0.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops

          # Install yq
          wget https://github.com/mikefarah/yq/releases/download/v4.48.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

          # Check installation
          sops --version
          yq --version
          jq --version

      - name: Verify secrets
        run: |
          cd wazuh/sops-scripts
          ./verify-secrets-dif.sh
